# Generated by Django 3.2.7 on 2021-11-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=9999999999)),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FullArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pulled', models.DateTimeField(verbose_name='date pulled from wikipedia')),
                ('formatted_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_page', to='wikipedia_converter.article')),
                ('original_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikipedia_converter.article')),
            ],
        ),
    ]
