# Generated by Django 3.2.7 on 2021-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pulled', models.DateTimeField(verbose_name='date pulled from wikipedia')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='receiving_date',
        ),
    ]
