# Generated by Django 4.0 on 2022-01-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullarticle',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikipedia_converter.user'),
        ),
    ]
