# Generated by Django 4.0 on 2022-01-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia_converter', '0002_fullarticle_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullarticle',
            old_name='borrower',
            new_name='user',
        ),
    ]
