# Generated by Django 3.2.7 on 2021-11-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia_converter', '0002_auto_20211122_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='null', max_length=9999999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
