# Generated by Django 3.2.7 on 2021-11-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia_converter', '0003_auto_20211122_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullarticle',
            name='formatted_page',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='formatted_page', to='wikipedia_converter.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullarticle',
            name='original_page',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='wikipedia_converter.article'),
            preserve_default=False,
        ),
    ]
